const fs = require('fs'), vm = require('vm'), assert = require('assert');
const src = fs.readFileSync('화면/app.js', 'utf8');
const ctx = {STATE: {queue: {items:[{status:'pending'}]}}, esc:s=>s, js:s=>s};
vm.createContext(ctx);
vm.runInContext(src.slice(src.indexOf('function explainError('), src.indexOf('function errorHelp(')), ctx);
let html = ctx.explainError('인월드 TTS 실패 HTTPSConnectionPool SSLError');
assert(html.includes('인월드와 통신이 끊겼어요'));
assert(!html.includes('나레이션(인월드) 설정을 확인하세요'));
html = ctx.explainError('자막 싱크 검사 실패', {script:'japanese.txt'});
assert(html.includes('문제 음성만 다시 만들기'));
assert(html.includes("repairNarration('japanese.txt')"));
assert(!html.includes("queueControl('resume')"));
assert(ctx.explainError('인월드 HTTP 429').includes('인월드 요청이 몰렸어요'));
console.log('Error help: 6 checks passed');
